trigger: none

parameters:

- name: environment
  displayName: Environment
  type: string
  default: QA
  values:
    - QA
    - Staging
    - Production

- name: testCategory
  displayName: Test Category
  type: string
  default: All
  values:
    - All
    - Smoke
    - Regression
    - Sanity

- name: headless
  displayName: Headless
  type: boolean
  default: true

variables:
  BuildConfiguration: Release

jobs:

- job: CrossBrowserExecution

  displayName: Cross Browser Execution

  strategy:

    matrix:

      Chrome:
        Browser: Chrome

      Firefox:
        Browser: Firefox

      Edge:
        Browser: Edge

  pool:
    vmImage: windows-latest

  steps:

  - checkout: self
    clean: true

  - task: UseDotNet@2
    displayName: Install .NET SDK
    inputs:
      packageType: sdk
      version: 9.0.x

  - task: DotNetCoreCLI@2
    displayName: Restore Packages
    inputs:
      command: restore
      projects: SpecFlowAutomationFramework.csproj

  - task: DotNetCoreCLI@2
    displayName: Build Project
    inputs:
      command: build
      projects: SpecFlowAutomationFramework.csproj
      arguments: '--configuration $(BuildConfiguration) --no-restore'

  - powershell: |

      Write-Host ""
      Write-Host "========================================"
      Write-Host " CROSS BROWSER EXECUTION "
      Write-Host "========================================"

      Write-Host "Browser      : $(Browser)"
      Write-Host "Environment  : ${{ parameters.environment }}"
      Write-Host "Category     : ${{ parameters.testCategory }}"
      Write-Host "Headless     : ${{ parameters.headless }}"
      Write-Host "Agent        : $(Agent.Name)"
      Write-Host "Machine      : $(Agent.MachineName)"
      Write-Host "========================================"

      $env:Browser="$(Browser)"
      $env:Environment="${{ parameters.environment }}"
      $env:Headless="${{ parameters.headless }}"

      if("${{ parameters.testCategory }}" -eq "All")
      {
          dotnet test SpecFlowAutomationFramework.csproj `
              --configuration $(BuildConfiguration) `
              --no-build `
              --logger "trx;LogFileName=$(Browser).trx"
              --collect:"XPlat Code Coverage"
      }
      else
      {
          dotnet test SpecFlowAutomationFramework.csproj `
              --configuration $(BuildConfiguration) `
              --no-build `
              --logger "trx;LogFileName=$(Browser).trx" `
              --collect:"XPlat Code Coverage" `
              --filter "Category=${{ parameters.testCategory }}"
      }

    displayName: Execute Tests
    continueOnError: true

  - task: PublishTestResults@2
    displayName: Publish Test Results
    condition: always()
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**/$(Browser).trx'
      mergeTestResults: true
      failTaskOnFailedTests: true
      testRunTitle: '$(Browser) Test Execution'

  - task: PublishPipelineArtifact@1
    displayName: Publish Reports
    condition: always()
    inputs:
      targetPath: '$(Build.SourcesDirectory)/Reports'
      artifact: Reports-$(Browser)


  - task: PublishCodeCoverageResults@2
    displayName: Publish Code Coverage
    condition: always()
    inputs:
      summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
      pathToSources: '$(Build.SourcesDirectory)'
      failIfCoverageEmpty: false
 