trigger:
- main

pr:
- main

parameters:

- name: browser
  displayName: Browser
  type: string
  default: Chrome
  values:
    - Chrome
    - Firefox
    - Edge

- name: environment
  displayName: Environment
  type: string
  default: QA
  values:
    - QA
    - Staging
    - Production

- name: testCategory
  displayName: Test Category
  type: string
  default: All
  values:
    - All
    - Smoke
    - Regression
    - Sanity

- name: headless
  displayName: Headless
  type: boolean
  default: true

pool:
  vmImage: windows-latest
  # For Self Hosted Agent use:
  # name: AutomationPool-20-07-26

variables:
  BuildConfiguration: Release

steps:

- checkout: self
  clean: true

- task: UseDotNet@2
  displayName: Install .NET SDK
  inputs:
    packageType: sdk
    version: 9.0.x

- task: DotNetCoreCLI@2
  displayName: Restore Packages
  inputs:
    command: restore
    projects: SpecFlowAutomationFramework.csproj

- task: DotNetCoreCLI@2
  displayName: Build Project
  inputs:
    command: build
    projects: SpecFlowAutomationFramework.csproj
    arguments: '--configuration $(BuildConfiguration) --no-restore'

- powershell: |

    Write-Host ""
    Write-Host "==========================================="
    Write-Host " AZURE DEVOPS CI PIPELINE "
    Write-Host "==========================================="

    Write-Host "Browser      : ${{ parameters.browser }}"
    Write-Host "Environment  : ${{ parameters.environment }}"
    Write-Host "Headless     : ${{ parameters.headless }}"
    Write-Host "Category     : ${{ parameters.testCategory }}"
    Write-Host "Agent        : $(Agent.Name)"
    Write-Host "Machine      : $(Agent.MachineName)"

    Write-Host "==========================================="

    $env:Browser="${{ parameters.browser }}"
    $env:Environment="${{ parameters.environment }}"
    $env:Headless="${{ parameters.headless }}"

    if("${{ parameters.testCategory }}" -eq "All")
    {
        dotnet test SpecFlowAutomationFramework.csproj `
            --configuration $(BuildConfiguration) `
            --no-build `
            --logger "trx;LogFileName=TestResults.trx"
    }
    else
    {
        dotnet test SpecFlowAutomationFramework.csproj `
            --configuration $(BuildConfiguration) `
            --no-build `
            --logger "trx;LogFileName=TestResults.trx" `
            --filter "Category=${{ parameters.testCategory }}"
    }

  displayName: Execute Test Scripts
  continueOnError: true

- task: PublishTestResults@2
  displayName: Publish Test Results
  condition: always()

  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/TestResults.trx'
    mergeTestResults: true
    failTaskOnFailedTests: false
    testRunTitle: CI Test Execution

- powershell: |

    $reportPath = "$(Build.SourcesDirectory)\Reports"

    if (Test-Path $reportPath)
    {
        Write-Host "Reports folder found."
        Write-Host "##vso[task.setvariable variable=ReportsExist]true"
    }
    else
    {
        Write-Host "Reports folder not found."
        Write-Host "##vso[task.setvariable variable=ReportsExist]false"
    }

  displayName: Check Reports Folder
  condition: always()

- task: PublishPipelineArtifact@1
  displayName: Publish Extent Reports
  condition: and(always(), eq(variables['ReportsExist'], 'true'))

  inputs:
    targetPath: '$(Build.SourcesDirectory)\Reports'
    artifact: 'Reports-$(Build.BuildId)'