############################################################
# NIGHTLY REGRESSION PIPELINE
############################################################

trigger: none

schedules:

- cron: "30 20 * * *"
  displayName: Nightly Regression (2:00 AM IST)

  branches:
    include:
      - shahidQA

  always: true

pool:
  vmImage: windows-latest
  # For Self Hosted Agent use:
  # name: AutomationPool-20-07-26

variables:

  BuildConfiguration: Release

  Browser: Chrome

  Environment: QA

  Headless: true

steps:

- checkout: self
  clean: true

- task: UseDotNet@2
  displayName: Install .NET SDK
  inputs:
    packageType: sdk
    version: 9.0.x

- task: DotNetCoreCLI@2
  displayName: Restore Packages
  inputs:
    command: restore
    projects: SpecFlowAutomationFramework.csproj

- task: DotNetCoreCLI@2
  displayName: Build Project
  inputs:
    command: build
    projects: SpecFlowAutomationFramework.csproj
    arguments: '--configuration $(BuildConfiguration) --no-restore'

- powershell: |

    Write-Host ""
    Write-Host "========================================"
    Write-Host " NIGHTLY REGRESSION EXECUTION "
    Write-Host "========================================"

    Write-Host "Browser        : $(Browser)"
    Write-Host "Environment    : $(Environment)"
    Write-Host "Category       : Regression"
    Write-Host "Headless       : $(Headless)"
    Write-Host "Agent          : $(Agent.Name)"
    Write-Host "Machine        : $(Agent.MachineName)"
    Write-Host "========================================"

    $env:Browser="$(Browser)"
    $env:Environment="$(Environment)"
    $env:Headless="$(Headless)"

    dotnet test SpecFlowAutomationFramework.csproj `
      --configuration $(BuildConfiguration) `
      --no-build `
      --logger "trx;LogFileName=NightlyRegression.trx" `
      --filter "Category=Regression"

  displayName: Execute Regression Suite

  continueOnError: true

- task: PublishTestResults@2
  displayName: Publish Test Results
  condition: always()

  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/NightlyRegression.trx'
    mergeTestResults: true
    failTaskOnFailedTests: false
    testRunTitle: Nightly Regression

- powershell: |

    $reportPath = "$(Build.SourcesDirectory)\Reports"

    if (Test-Path $reportPath)
    {
        Write-Host "Reports folder found."
        Write-Host "##vso[task.setvariable variable=ReportsExist]true"
    }
    else
    {
        Write-Host "Reports folder not found."
        Write-Host "##vso[task.setvariable variable=ReportsExist]false"
    }

  displayName: Check Reports Folder
  condition: always()

- task: PublishPipelineArtifact@1
  displayName: Publish Extent Reports
  condition: and(always(), eq(variables['ReportsExist'], 'true'))

  inputs:
    targetPath: '$(Build.SourcesDirectory)\Reports'
    artifact: Nightly-Regression-Reports