trigger:
- main

pool:
  name: 'AutomationPool-20-07-26'
  demands:
  - Browser -equals Chrome

steps:

# Install .NET SDK
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '9.0.307'

# Restore NuGet packages
- task: DotNetCoreCLI@2
  displayName: 'Restore Packages'
  inputs:
    command: 'restore'
    projects: '**/*.sln'

# Build Solution
- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '--configuration Release'

# Run Tests
- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: '--configuration Release'

# Publish Test Results
- task: DotNetCoreCLI@2
  displayName: Run Test Scripts
  inputs:
    command: test
    projects: '**/*.csproj'
    arguments: >
      --configuration Release
      --logger "trx;LogFileName=TestResults.trx"